💄feature(user): side elements certification
AtoLrn/projet_annuel_IW1 pull request #43
Opened 2022-03-22 20:08 UTC by Iz0nite

# Pull Request

### Description
I added elements to implement the description of the certification demand + two dowlnoad button for id document and official document.

![image](https://user-images.githubusercontent.com/62487421/159566771-0ac10c73-3299-4075-a693-f1fd07dfbb23.png)

### Pull Request Type

-   [x] Feature
-   [ ] Fix
-   [ ] Hotfix
-   [ ] Docker

### By pushing this PR i assumed that i've:

-   [x] Tested My Code
-   [x] Did it a way it is reusable
-   [x] Documented the coode
-   [x] Moved the Trello Card

2022-03-27 15:15 UTC, AtoLrn commented
Comment on fait la demande ?

2022-03-27 15:16 UTC, AtoLrn commented
![image](https://user-images.githubusercontent.com/26856078/160288303-fd7c3d9d-b6c7-4b03-b319-fb890ef1f6a6.png)
C'est normal le visuel de la request ?

2022-03-27 15:20 UTC, AtoLrn requested changes
Pourrais tu:

Mettre à jour l'init sql
indiquer la route pour aller sur la page
Me faire un bisous

2022-03-27 15:46 UTC, NoePigeau commented on www/Model/Certification.class.php
> +                /*                "sizeIdFile" => [
enleve les commentaires si tu les utilise pas

2022-03-27 15:46 UTC, NoePigeau commented on www/assets/src/js/certification.js
> +    let idDocumentBtn = $('#idDocument')
en vrai pour ce genre de truc j'aime bien mettre direct 
$('#idDocument')
           .attr(....)
           .attr(....)
ca evite de déclarer trop de variables mais c'est du détails en vrai je rien a dire d'autre mdr

2022-03-27 15:49 UTC, NoePigeau commented
ah oui aussi armand, le textarea des certif mets la propriété css resize: none; sinon on peut modifer sa taille et c'est pas ouf

2022-03-28 17:15 UTC, Iz0nite commented
> ![image](https://user-images.githubusercontent.com/26856078/160288303-fd7c3d9d-b6c7-4b03-b319-fb890ef1f6a6.png) C'est normal le visuel de la request ?

Je ferais l'intégration plus tard

2022-03-28 17:15 UTC, Iz0nite commented
> Pourrais tu:
> 
> Mettre à jour l'init sql indiquer la route pour aller sur la page Me faire un bisous

- c'est fait
- /certification-request
- *fais un gros bisous

2022-03-28 17:16 UTC, armand-dfl commented on www/Model/Certification.class.php
> +                /*                "sizeIdFile" => [
Modifié

2022-03-28 17:16 UTC, Iz0nite commented on www/assets/src/js/certification.js
> +    let idDocumentBtn = $('#idDocument')
Je t'avoue que je m'y retrouve mieux comme ça

2022-03-28 17:16 UTC, Iz0nite commented
> ah oui aussi armand, le textarea des certif mets la propriété css resize: none; sinon on peut modifer sa taille et c'est pas ouf. tu peux le mettre en globale sur tout les text-area

Modifié

2022-04-07 18:32 UTC, NoePigeau approved these changes

2022-04-07 20:10 UTC, AtoLrn approved these changes
oui

2022-04-07 20:11 UTC, merged